# Start from the official Go image as the base
FROM golang:1.19

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files to the working directory
COPY go.mod go.sum ./

# Download and install the Go dependencies
RUN go mod download

# Copy the rest of the application source code to the working directory
COPY . .

# Build the Go application
RUN go build -o main .

# Expose the port on which the API will listen
EXPOSE 8000

# Run the Go application when the container starts
CMD ["./main"]
